### ISSUE TITLE
How to show sane errors for helper files? 

### ISSUE THREAD

**Issue by MikaelElkiaer** [mrjosh/helm-ls#90]
I have a bunch of helper templates - e.g. `templates/_example.tpl`.
With the default config, they will show a bunch of errors, as they are interpreted as Kubernetes files - e.g. if indentation is wrong or it contains the same key, it will show as an error.

![image](https://github.com/mrjosh/helm-ls/assets/2102306/926dc227-6cbd-490e-8c6d-7d3729777139)

I have tried overriding the config with

```lua
settings = {
  ['helm-ls'] = {
    yamlls = {
      config = {
        schemas = {
          kubernetes = "templates/**/[!_]*"
        },
      }
    },
  },
},
```

But this will still show errors as the file is interpreted as a single yaml file, despite it containing multiple `define`s.

**Comment by qvalentin** [comment]
Hi thanks for reporting, this requires a fix, here are some possible ways to implement it:

1. Hide certain diagnostics inside define blocks: E.g. all diagnostics like "Property foo is not allowed"
2. Disable yamlls for .tpl files (this is kind of obvious, I don't know why I did not think of this earlier)
3. Allow configuring a pattern for files which should have yamlls enabled/disabled.

I think your config change is not working because yamlls only allows very primitive glob patterns.

**Comment by MikaelElkiaer** [comment]
Thanks for clarifying.
And well done on the PR! Looking forward to this improvement.
